version: "3"
services:

    postgres:
        image: postgres:13.3-alpine
        container_name: apiserver-postgres
        command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr", "-c", "log_duration=on"]
        volumes:
          - dpands-pgdata:/var/lib/postgresql/data
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: apiserver
        ports:
          - 5432:5432

volumes:
    dpands-pgdata:
