"""create admin user

Revision ID: 3cce72e4cea7
Revises: 2665c0e20674
Create Date: 2021-07-20 11:51:27.485233

"""
from migrations.adb import adb
from app.core.utils.password import get_password_hash
from app.users.models import User


# revision identifiers, used by Alembic.
revision = '3cce72e4cea7'
down_revision = '2665c0e20674'
branch_labels = None
depends_on = None


@adb.async_migration
async def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    await User.objects.get_or_create(
        email='admin@admin.com',
        username='admin',
        password=get_password_hash('admin'),
        is_active=True,
    )
    # ### end Alembic commands ###


@adb.async_migration
async def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    await User.objects.filter(username='admin').delete()
    # ### end Alembic commands ###
