"""add superuser

Revision ID: 6e653c68eb31
Revises: ce12920f8334
Create Date: 2021-07-09 20:17:12.036308

"""
from alembic import op
import sqlalchemy as sa
from apiserver.core.utils.password import get_password_hash

# revision identifiers, used by Alembic.
revision = '6e653c68eb31'
down_revision = 'ce12920f8334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    password_ = get_password_hash('admin')
    op.execute(f"INSERT INTO public.\"users\" (email, password, username, is_active, created_at, updated_at) VALUES('admin@admin.com', '{password_}', 'admin', true, now(), now());")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM public.\"users\" WHERE username = 'admin';")
    # ### end Alembic commands ###
