"""add superuser

Revision ID: 6e653c68eb31
Revises: ce12920f8334
Create Date: 2021-07-09 20:17:12.036308

"""
from migrations.utils.apiserver import use_db_async
from apiserver.core.utils.password import get_password_hash
from apiserver.users.models import User

# revision identifiers, used by Alembic.
revision = '6e653c68eb31'
down_revision = 'ce12920f8334'
branch_labels = None
depends_on = None


@use_db_async
async def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    await User.objects.get_or_create(
        email='admin@admin.com',
        username='admin',
        password=get_password_hash('admin'),
        is_active=True,
    )
    # ### end Alembic commands ###

@use_db_async
async def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    await User.objects.filter(username='admin').delete()
    # ### end Alembic commands ###
