"""Create superuser

Revision ID: 16f836c4a350
Revises: eb7c63e4b6e2
Create Date: 2021-06-30 23:30:55.036035

"""
from alembic import op
from core.utils.password import get_password_hash

# revision identifiers, used by Alembic.
revision = '16f836c4a350'
down_revision = 'eb7c63e4b6e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    password_ = get_password_hash('admin')
    op.execute(f"INSERT INTO public.\"user\" (email, password, username, active, created_at, updated_at) VALUES('admin@admin.com', '{password_}', 'admin', true, now(), now());")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"DELETE FROM public.\"user\" WHERE username = 'admin';")
    # ### end Alembic commands ###
