"""create superuser

Revision ID: 7b81be2266fd
Revises: 2baf746440b9
Create Date: 2021-07-08 17:09:45.663929

"""
from alembic import op
import sqlalchemy as sa
from core.utils.password import get_password_hash

# revision identifiers, used by Alembic.
revision = '7b81be2266fd'
down_revision = '2baf746440b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    password_ = get_password_hash('admin')
    op.execute(f"INSERT INTO public.\"users\" (email, password, username, is_active, created_at, updated_at) VALUES('admin@admin.com', '{password_}', 'admin', true, now(), now());")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"DELETE FROM public.\"users\" WHERE username = 'admin';")
    # ### end Alembic commands ###
